"""
Django's settings for iplants_project project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import os

from neomodel import config
import mongoengine
from configparser import RawConfigParser

db_configs = RawConfigParser()
db_configs.read('/conf/iplantdb.conf')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g2r+2-y@euae!tc94ln2&-&8i(@vkv__w9npe-hvu0@6*9)5bl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [str(db_configs.get('iplants-databases-configurations', 'iplants_api'))]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'iplants_neo',
    'iplants_mongo',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iplants_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iplants_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


MONGODB_DATABASES = {
    "default": {
        "name": str(db_configs.get('iplants-databases-configurations', 'mongodb_name')),
        "host": str(db_configs.get('iplants-databases-configurations', 'mongodb_host')),
        "port": int(db_configs.get('iplants-databases-configurations', 'mongodb_port')),
    }
}

NEO4J_DATABASES = {
    "default": {
        "username": str(db_configs.get('iplants-databases-configurations', 'neo4j_user')),
        "password": str(db_configs.get('iplants-databases-configurations', 'neo4j_pass')),
        "host": str(db_configs.get('iplants-databases-configurations', 'neo4j_host')),
        "port": int(db_configs.get('iplants-databases-configurations', 'neo4j_port'))
    }
}


db = 'default'

neo4j_url = "bolt://" + NEO4J_DATABASES[db]["username"] + ':' + NEO4J_DATABASES[db]["password"] + '@' + \
            NEO4J_DATABASES[db]["host"] + ':' + str(NEO4J_DATABASES[db]["port"])
config.DATABASE_URL = neo4j_url

mongoengine.connect(MONGODB_DATABASES[db]["name"], host=MONGODB_DATABASES[db]["host"],
                    port=MONGODB_DATABASES[db]["port"])

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # YOUR SETTINGS
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'iplants API',
    'DESCRIPTION': 'API to get data from iplants repository. Searches can be performed using biocyc identifiers.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
}
